apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-test-app1
spec:
  selector:
    matchLabels:
      app: argo-test-app1
  template:
    metadata:
      labels:
        app: argo-test-app1
    spec:
      containers:
        - name: argo-test-app1
          image: kerhalish/argo-test-app1:{{ .Values.env.APP_VERSION }}
          command: ["sh", "-c", "sleep infinity"]
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
